# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

registries:
  spring-boot-common-github-packages:
    type: maven-repository
    url: https://maven.pkg.github.com/ministryofjustice/laa-spring-boot-common
    username: farrellm
    password: ${{ secrets.DEPENDABOT_PAT }}

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    registries:
      - maven-central
      - spring-boot-common-github-packages
    groups:
      gradle-updates:
        exclude-patterns:
          - "uk.gov.laa.*"
      internal-packages:
        patterns:
          - "uk.gov.laa.*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      github-actions:
        patterns:
          - "**"