name: "Deploy branch"
description: 'Deploy docker image of branch to namespace with an ingress based on branch name'
inputs:
  ecr-repository:
    description: "ECR repository"
    required: true
  ecr-region:
    description: "ECR region"
    required: true
  ecr-role-to-assume:
    description: "ECR role to assume"
    required: true
  kube-cert:
    description: "Kubernetes cluster authentication certificate"
    required: true
  kube-token:
    description: "Kubernetes cluster authentication token"
    required: true
  kube-cluster:
    description: "Kubernetes cluster name"
    required: true
  kube-namespace:
    description: "Kubernetes cluster namespace"
    required: true
  app-environment:
    description: "environment to which the app is being deployed [staging, production, etc]"
    required: true
  image-tag:
    description: "Docker image tag to deploy"
    required: true
  oidc-mock-image-tag:
    description: "OIDC mock image tag to deploy (preview only)"
    required: false

outputs:
  branch-name:
    description: "Extracted branch name"
    value: ${{ steps.extract_release_name.outputs.branch-name }}
  release-name:
    description: "Extracted release name"
    value: ${{ steps.extract_release_name.outputs.release-name }}

runs:
  using: "composite"
  steps:

    - name: Extract release name
      id: extract_release_name
      uses: ./.github/actions/get_release_name

    - name: Authenticate to the cluster
      uses: ministryofjustice/laa-reusable-github-actions/.github/actions/authenticate_to_cluster@2aa2676c3cd9876ec7037ee8b3d729d0306cb7c6
      with:
        kube-cert: ${{ inputs.kube-cert }}
        kube-token: ${{ inputs.kube-token }}
        kube-cluster: ${{ inputs.kube-cluster }}
        kube-namespace: ${{ inputs.kube-namespace }}

    - name: Assume role in Cloud Platform
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.ecr-role-to-assume }}
        aws-region: ${{ inputs.ecr-region }}

    - name: Docker login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        mask-password: 'true'

    - name: Set helm chart app version
      shell: bash
      env:
        IMAGE_TAG: ${{ inputs.image-tag }}
      run: |
        yq eval-all "( .appVersion = \"${IMAGE_TAG}\" )" -i .helm/submit-a-bulk-claim/Chart.yaml
        cat .helm/submit-a-bulk-claim/Chart.yaml

    - name: Helm deployment of branch
      id: helm-install
      shell: bash
      env:
        ECR_REPOSITORY: ${{ inputs.ecr-repository }}
        ECR_REGION: ${{ inputs.ecr-region }}
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ inputs.image-tag }}
        KUBE_NAMESPACE: ${{ inputs.kube-namespace }}
        VALUES_FILE: .helm/submit-a-bulk-claim/values/env-${{ inputs.app-environment }}.yaml
        PREVIEW_VALUES_FILE: .helm/submit-a-bulk-claim/values/env-${{ inputs.app-environment }}-preview.yaml
        RELEASE_NAME: ${{ steps.extract_release_name.outputs.release-name }}
        BRANCH_NAME: ${{ steps.extract_release_name.outputs.branch-name }}
        OIDC_IMAGE_TAG: ${{ inputs.oidc-mock-image-tag }}
      run: |
        echo "Deploying image tag: $IMAGE_TAG under release name: $RELEASE_NAME to namespace: $KUBE_NAMESPACE"

        values_args=("--values" "$VALUES_FILE")

        if [ "$BRANCH_NAME" != "main" ] && [ -f "$PREVIEW_VALUES_FILE" ]; then
          values_args+=("--values" "$PREVIEW_VALUES_FILE")
          helm upgrade "${RELEASE_NAME}-redis" oci://registry-1.docker.io/bitnamicharts/redis \
            -f .helm/bitnami_redis/values.yaml \
            --namespace "$KUBE_NAMESPACE" \
            --install --wait --timeout=10m
          oidc_values_args=(
            --set image.repository="${ECR_REGISTRY}/${ECR_REPOSITORY}"
            --set sabc.releaseName="${RELEASE_NAME}"
          )
          if [ -n "$OIDC_IMAGE_TAG" ]; then
            oidc_values_args+=(--set image.tag="${OIDC_IMAGE_TAG}")
          fi
          helm upgrade "${RELEASE_NAME}-oidc-mock" .helm/oidc-mock \
            --namespace "$KUBE_NAMESPACE" \
            "${oidc_values_args[@]}" \
            --install --wait --timeout=10m
        fi

        helm upgrade "$RELEASE_NAME" .helm/submit-a-bulk-claim \
          --namespace "$KUBE_NAMESPACE" \
          --set global.image.repository="${ECR_REGISTRY}/${ECR_REPOSITORY}" \
          "${values_args[@]}" \
          --install \
          --wait --timeout=10m
  
        IMAGES=$(helm get manifest "$RELEASE_NAME" --namespace "$KUBE_NAMESPACE" | yq -o=json '.' | jq -sc \
            "[.[] | select(.kind == \"Deployment\") | select(.spec.template.spec.containers[0].image | contains(\"$ECR_REGISTRY/$ECR_REPOSITORY\")) | {image_version_tag: .metadata.labels.appVersion, release_tag: .metadata.name}]")

        # Use heredoc for multi-line output safety
        printf 'images<<EOF\n%s\nEOF\n' "$IMAGES" >> "$GITHUB_OUTPUT"
        
        echo "Deployed Images: $(echo "$IMAGES" | jq)"

    - name: Update image tags
      uses: ./.github/actions/ecr-update-image-tags
      with:
        images: ${{ steps.helm-install.outputs.images }}
        role_to_assume: ${{ inputs.ecr-role-to-assume }}
        aws_region: ${{ inputs.ecr-region }}
        ecr_repository: ${{ inputs.ecr-repository }}
