name: "Extract Release Name"
description: "Converts branch name into a formatted Helm release name"
inputs:
  branch_name:
    description: "The original branch name"
    required: true
outputs:
  release_name:
    description: "Formatted release name"
    value: ${{ steps.release.outputs.release_name }}
runs:
  using: "composite"
  steps:
    - id: release
      shell: bash
      env:
        BRANCH_NAME: ${{ inputs.branch_name }}
      run: |
        truncated_branch=$(echo "$BRANCH_NAME" | tr '[:upper:]' '[:lower:]' | tr -s ' _/[]().' '-' | cut -c1-9 | sed 's/-$//')
        echo "release_name=${truncated_branch}" >> $GITHUB_OUTPUT
        echo "release_name being exported: ${truncated_branch}"
