name: "Cleanup branch"
description: 'Cleanup the UAT environment resources after a branch is merged into main'
inputs:
  kube-cert:
    description: "Kubernetes cluster authentication certificate"
    required: true
  kube-token:
    description: "Kubernetes cluster authentication token"
    required: true
  kube-cluster:
    description: "Kubernetes cluster name"
    required: true
  kube-namespace:
    description: "Kubernetes cluster namespace"
    required: true

runs:
  using: "composite"
  steps:

    - name: Get release name
      id: extract_release_name
      uses: ./.github/actions/get_release_name

    - name: Authenticate to the cluster
      uses: ministryofjustice/laa-reusable-github-actions/.github/actions/authenticate_to_cluster@2aa2676c3cd9876ec7037ee8b3d729d0306cb7c6
      with:
        kube-cert: ${{ inputs.kube-cert }}
        kube-token: ${{ inputs.kube-token }}
        kube-cluster: ${{ inputs.kube-cluster }}
        kube-namespace: ${{ inputs.kube-namespace }}

    - name: Delete preview release
      shell: bash
      run: helm uninstall ${{ steps.extract_release_name.outputs.release-name }} --namespace ${{ inputs.kube-namespace }}

    - name: Delete preview release's redis instance
      shell: bash
      run: helm uninstall ${{ steps.extract_release_name.outputs.release-name }}-redis --namespace ${{ inputs.kube-namespace }}

    - name: Delete preview release's oidc mock
      shell: bash
      run: helm uninstall ${{ steps.extract_release_name.outputs.release-name }}-oidc-mock --namespace ${{ inputs.kube-namespace }}

    - name: Delete preview release's redis pvc (persistent volume claim)
      shell: bash
      run: kubectl delete pvc -l app.kubernetes.io/instance="${{ steps.extract_release_name.outputs.release-name }}-redis" --namespace ${{ inputs.kube-namespace }}
