package uk.gov.justice.laa.payments.submit.util;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import org.springframework.stereotype.Component;

/**
 * Detects whether an uploaded bulkload file matches the LAA Bulk Load Spreadsheet naming
 * convention.
 *
 * <p>Filenames generated by the spreadsheet carry a provider/period-specific prefix (e.g. {@code
 * CivilBulkload0P322FJAN2026_v2.00.csv}) which is ignored by this util — only the filename's suffix
 * is checked: {@code vN.NN.csv} (e.g. {@code ...v2.00.csv}) for the standard case, or {@code
 * -mac-vN.NN.csv} (e.g. {@code ...-mac-v1.42.csv}) for the Mac variant, which is being
 * decommissioned but some supplied may still use.
 */
@Component
public class BulkLoadSpreadsheetFilenameUtil {

  private static final Pattern MAC_PATTERN =
      Pattern.compile("-mac-v(\\d+\\.\\d{2})\\.csv\\z", Pattern.CASE_INSENSITIVE);

  private static final Pattern STANDARD_PATTERN =
      Pattern.compile("v(\\d+\\.\\d{2})\\.csv\\z", Pattern.CASE_INSENSITIVE);

  public BulkLoadSpreadsheetFilenameMatch detect(String filename) {
    if (filename == null || filename.isBlank()) {
      return BulkLoadSpreadsheetFilenameMatch.noMatch();
    }

    Matcher macMatcher = MAC_PATTERN.matcher(filename);
    if (macMatcher.find()) {
      return new BulkLoadSpreadsheetFilenameMatch(true, true, macMatcher.group(1));
    }

    Matcher standardMatcher = STANDARD_PATTERN.matcher(filename);
    if (standardMatcher.find()) {
      return new BulkLoadSpreadsheetFilenameMatch(true, false, standardMatcher.group(1));
    }

    return BulkLoadSpreadsheetFilenameMatch.noMatch();
  }
}
