name: "Update images in ECR with the given tags"
description: "Apply release tags to existing ECR images"

inputs:
  images:
    description: "A JSON string containing current images tags and tags to add"
    required: true
  role_to_assume:
    description: "AWS role to assume"
    required: true
  aws_region:
    description: "AWS region"
    required: true
  ecr_repository:
    description: "AWS ECR repository"
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure aws credentials
      uses: aws-actions/configure-aws-credentials@v5
      with:
        role-to-assume: ${{ inputs.role_to_assume }}
        aws-region: ${{ inputs.aws_region }}

    - name: Login ecr
      uses: aws-actions/amazon-ecr-login@v2
      id: login-ecr

    - name: Update tags in ECR
      shell: bash
      env:
        IMAGES: ${{ inputs.images }}
        ECR_REPOSITORY: ${{ inputs.ecr_repository }}
      run: |
        set -euo pipefail
        IFS=$'\n\t'
        echo "$IMAGES" | jq -c '.[]' | while read -r image; do
          image_version_tag=$(echo "$image" | jq -r '.image_version_tag')
          release_tag=$(echo "$image" | jq -r '.release_tag')

          current_tags=$(aws ecr describe-images \
            --repository-name "$ECR_REPOSITORY" \
            --image-ids imageTag="$image_version_tag" \
            --query 'imageDetails[0].imageTags' \
            --output json)
          echo "Current tags for '$image_version_tag': $current_tags"

          if echo "$current_tags" | jq -e --arg tag "$release_tag" 'index($tag)' > /dev/null; then
            echo "Image \`$image_version_tag\` already tagged \`$release_tag\`" >> "$GITHUB_STEP_SUMMARY"
            echo "Image '$image_version_tag' already tagged '$release_tag'. Skipping..."
          else
            echo "Updating image '$image_version_tag' with tag '$release_tag'..."
            image_manifest=$(aws ecr batch-get-image \
              --repository-name "$ECR_REPOSITORY" \
              --image-ids imageTag="$image_version_tag" \
              --output text \
              --query 'images[].imageManifest')
            aws ecr put-image \
              --repository-name "$ECR_REPOSITORY" \
              --image-tag "$release_tag" \
              --image-manifest "$image_manifest"
            echo "Image \`$image_version_tag\` updated with tag \`$release_tag\`" >> "$GITHUB_STEP_SUMMARY"
            echo "Image '$image_version_tag' updated with tag '$release_tag'."
          fi
        done
