name: "Authenticate to the EKS cluster"

on:
  workflow_call:
    inputs:
      kube_cluster:
        description: 'The EKS cluster'
        required: true
        type: string
      kube_namespace:
        description: 'The EKS namespace'
        required: true
        type: string
      kube_token:
        description: 'The EKS authentication token'
        required: true
        type: string
      kube_cert:
        description: 'The EKS TLS certificate'
        required: true
        type: string

runs:
  using: "composite"
  steps:
    - name: Authenticate to EKS cluster
      shell: bash
      env:
        KUBE_CLUSTER: ${{ inputs.kube_cluster }}
        KUBE_NAMESPACE: ${{ inputs.kube_namespace }}
        KUBE_TOKEN: ${{ inputs.kube_token }}
        KUBE_CERT: ${{ inputs.kube_cert }}
      run: |
        echo "$KUBE_CERT" > ca.crt
        kubectl config set-cluster $KUBE_CLUSTER --certificate-authority=./ca.crt --server=https://$KUBE_CLUSTER
        kubectl config set-credentials deploy-user --token=$KUBE_TOKEN
        kubectl config set-context $KUBE_CLUSTER --cluster=$KUBE_CLUSTER --user=deploy-user --namespace=$KUBE_NAMESPACE
        kubectl config use-context $KUBE_CLUSTER