services:
  sabc-ui:
    image: ${REGISTRY}/${REPO}:${IMAGE_TAG}
    container_name: submit-a-bulk-claim-app
    environment:
      SERVER_MAX_FILE_SIZE: 50MB
      UPLOAD_MAX_FILE_SIZE: 10MB
      AUTH_CLIENT_ID: ${AUTH_CLIENT_ID}
      AUTH_CLIENT_SECRET: ${AUTH_CLIENT_SECRET}
      AUTH_SCOPE: ${AUTH_SCOPE}
      AUTH_TENANT_ID: ${AUTH_TENANT_ID}
      SDS_API_URL: ${SDS_API_URL}
      CLAIM_API_URL: http://claims-api:8080
      CLAIMS_API_ACCESS_TOKEN: f67f968e-b479-4e61-b66e-f57984931e56
      REST_CLIENT_CONNECT_TIMEOUT: 5000
      REST_CLIENT_READ_TIMEOUT: 40000
      REDIS_HOST: redis://redis:6379
      SPRING_PROFILES_ACTIVE: ${SUBMIT_SPRING_PROFILES_ACTIVE:-oidc}
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      IS_NIL_SUBMISSION_ENABLED: "true"
      IS_ALTERNATIVE_CLAIM_VIEW_ENABLED: "true"
    ports:
      - "8082:8082"
      - "8182:8081"
      - "5082:5005"
    depends_on:
      - redis
      - claims-api
      - event-service
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: redis:8-alpine
    container_name: redis
    ports:
      - "6382:6379"

  claims-api:
    build:
      context: ../../laa-data-claims-parent/laa-data-claims-api
      dockerfile: Dockerfile
    container_name: data-claims-api-app
    ports:
      - "8180:8081"

  event-service:
    build:
      context: ../../laa-data-claims-parent/laa-data-claims-event-service
      dockerfile: Dockerfile_internal
    container_name: data-claims-event-service-app
    ports:
      - "8181:8081"