services:
  sabc-ui:
    image: ${REGISTRY}/${REPO}:${IMAGE_TAG}
    container_name: submit-a-bulk-claim-app
    environment:
      AUTH_CLIENT_ID: ${AUTH_CLIENT_ID}
      AUTH_CLIENT_SECRET: ${AUTH_CLIENT_SECRET}
      AUTH_SCOPE: ${AUTH_SCOPE}
      AUTH_TENANT_ID: ${AUTH_TENANT_ID}
      SDS_API_URL: ${SDS_API_URL}
      FEE_SCHEME_PLATFORM_API_URL: ${FEE_SCHEME_PLATFORM_API_URL}
      FEE_SCHEME_PLATFORM_API_ACCESS_TOKEN: ${FEE_SCHEME_PLATFORM_API_ACCESS_TOKEN}
      PROVIDER_DETAILS_API_URL: ${PROVIDER_DETAILS_API_URL}
      PROVIDER_DETAILS_API_HOSTNAME: ${PROVIDER_DETAILS_API_HOSTNAME}
      PROVIDER_DETAILS_API_ACCESS_TOKEN: ${PROVIDER_DETAILS_API_ACCESS_TOKEN}
      SUBMIT_SPRING_PROFILES_ACTIVE: ${SUBMIT_SPRING_PROFILES_ACTIVE}
      LAA_ACCOUNTS: ${LAA_ACCOUNTS}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
    ports:
      - "8082:8082"
      - "8182:8081"
      - "5082:5005"
    depends_on:
      - redis
      - local-postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: redis:8-alpine
    container_name: redis
    ports:
      - "6382:6379"

  local-postgres:
    image: postgres:18.1-alpine
    container_name: local-postgres
    environment:
      POSTGRES_DB: laa_data_claims_api_dev
      POSTGRES_USER: user
      POSTGRES_PASSWORD: dev
    ports:
      - "5432:5432"