name: Deploy main

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        required: true
        default: "patch"
        description: "Release type"
        options: [ "patch", "minor", "major" ]

jobs:
  release:
    uses: ministryofjustice/laa-ccms-common-workflows/.github/workflows/gradle-build-and-publish.yml@4daa796eff475c7a107e17daf4e4882b8a1b949b # v2.3.0
    permissions:
      contents: write
      packages: write
    with:
      build_command: ':laa-submit-a-bulk-claim-ui:assemble'
      junit_results: 'false'
      junit_report: 'false'
      checkstyle_report: 'false'
      jacoco_coverage_report: 'false'
      semgrep_check: 'true'
      java_version: 25
      release_type: ${{ github.event.inputs.release_type || '' }}
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}

  pact-test:
    needs: [ release ]
    uses: ministryofjustice/laa-ccms-common-workflows/.github/workflows/pact-and-publish.yml@4daa796eff475c7a107e17daf4e4882b8a1b949b # v2.3.0
    permissions:
      contents: write
      packages: write
    with:
      pacticipant_name: "laa-submit-a-bulk-claim"
      pact_test_task: "pactTest"
      publish_pact_results: true
      git_branch: 'main'
      pact_tags: '${{ needs.release.outputs.published_artifact_version }},candidate'
      java_version: 25
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      pact_broker_url: 'https://laa-data-pact-broker.apps.live.cloud-platform.service.justice.gov.uk/'
      pact_broker_username: ${{ secrets.PACT_BROKER_USERNAME }}
      pact_broker_password: ${{ secrets.PACT_BROKER_PASSWORD }}

  ecr-publish-image:
    needs: [ release ]
    uses: ministryofjustice/laa-ccms-common-workflows/.github/workflows/ecr-publish-image.yml@4daa796eff475c7a107e17daf4e4882b8a1b949b # v2.3.0
    permissions:
      contents: read
      id-token: write
      security-events: write
    with:
      jar_subproject: 'laa-submit-a-bulk-claim-ui'
      image_version: ${{ format('{0}-{1}', vars.IMAGE_PREFIX, needs.release.outputs.published_artifact_version) }}
      image_scan_severity: 'critical'
      image_scan_fail_on: 'all'
      java_version: 25
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      ecr_repository: ${{ vars.LAA_SUBMIT_A_BULK_CLAIM_ECR_REPOSITORY }}
      ecr_region: ${{ vars.LAA_SUBMIT_A_BULK_CLAIM_ECR_REGION }}
      ecr_role_to_assume: ${{ secrets.LAA_SUBMIT_A_BULK_CLAIM_ECR_ROLE_TO_ASSUME }}
      snyk_client_id: ${{ secrets.SNYK_CLIENT_ID }}
      snyk_client_secret: ${{ secrets.SNYK_CLIENT_SECRET }}


  deploy-uat:
    needs:
      - ecr-publish-image
      - pact-test
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/helm-deploy.yml
    with:
      environment: uat
      deployment_name: uat
      claim_api_environment_name: main
      image_tag: ${{ needs.ecr-publish-image.outputs.published_image_version }}
    secrets:
      pact_broker_username: ${{ secrets.PACT_BROKER_USERNAME }}
      pact_broker_password: ${{ secrets.PACT_BROKER_PASSWORD }}
      KUBE_CLUSTER: ${{ secrets.KUBE_CLUSTER }}
      KUBE_NAMESPACE: ${{ secrets.KUBE_NAMESPACE }}
      KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
      KUBE_CERT: ${{ secrets.KUBE_CERT }}
      LAA_SUBMIT_A_BULK_CLAIM_ECR_ROLE_TO_ASSUME: ${{ secrets.LAA_SUBMIT_A_BULK_CLAIM_ECR_ROLE_TO_ASSUME }}

  deploy-staging:
    needs:
      - ecr-publish-image
      - pact-test
      - deploy-uat
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/helm-deploy.yml
    with:
      environment: staging
      deployment_name: stg
      claim_api_environment_name: stg
      image_tag: ${{ needs.ecr-publish-image.outputs.published_image_version }}
    secrets:
      pact_broker_username: ${{ secrets.PACT_BROKER_USERNAME }}
      pact_broker_password: ${{ secrets.PACT_BROKER_PASSWORD }}
      KUBE_CLUSTER: ${{ secrets.KUBE_CLUSTER }}
      KUBE_NAMESPACE: ${{ secrets.KUBE_NAMESPACE }}
      KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
      KUBE_CERT: ${{ secrets.KUBE_CERT }}
      LAA_SUBMIT_A_BULK_CLAIM_ECR_ROLE_TO_ASSUME: ${{ secrets.LAA_SUBMIT_A_BULK_CLAIM_ECR_ROLE_TO_ASSUME }}

  deploy-production:
    needs:
      - ecr-publish-image
      - pact-test
      - deploy-staging
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/helm-deploy.yml
    with:
      environment: production
      deployment_name: prod
      claim_api_environment_name: prod
      image_tag: ${{ needs.ecr-publish-image.outputs.published_image_version }}
    secrets:
      pact_broker_username: ${{ secrets.PACT_BROKER_USERNAME }}
      pact_broker_password: ${{ secrets.PACT_BROKER_PASSWORD }}
      KUBE_CLUSTER: ${{ secrets.KUBE_CLUSTER }}
      KUBE_NAMESPACE: ${{ secrets.KUBE_NAMESPACE }}
      KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
      KUBE_CERT: ${{ secrets.KUBE_CERT }}
      LAA_SUBMIT_A_BULK_CLAIM_ECR_ROLE_TO_ASSUME: ${{ secrets.LAA_SUBMIT_A_BULK_CLAIM_ECR_ROLE_TO_ASSUME }}
