name: Deploy feature

on:
  push:
    branches:
      - 'feature/*'

permissions:
  contents: read

jobs:
  define-feature-version:
    runs-on: ubuntu-latest
    outputs:
      feature_version: ${{ steps.get-feature-version.outputs.feature_version }}
    steps:
      - uses: actions/checkout@v4
      - uses: ministryofjustice/laa-ccms-common-workflows/.github/actions/remove-prefix@v1
        id: get-feature-name
        with:
          string: ${{ github.ref_name }}
          prefix: 'feature/'
      - name: Get feature version
        id: get-feature-version
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          echo "feature_version=${{ steps.get-feature-name.outputs.result }}-${COMMIT_HASH}-SNAPSHOT" >> $GITHUB_OUTPUT
          echo "Feature version: ${{ steps.get-feature-name.outputs.result }}-${COMMIT_HASH}-SNAPSHOT"

  assemble:
    uses: ministryofjustice/laa-ccms-common-workflows/.github/workflows/gradle-build-and-publish.yml@v1
    permissions:
      contents: write
      packages: write
    with:
      build_command: 'assemble'
      publish_package: 'false'
      override_version: ${{ needs.define-feature-version.outputs.feature_version }}
      junit_results: 'false'
      junit_report: 'false'
      checkstyle_report: 'false'
      jacoco_coverage_report: 'false'
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}

  ecr-publish-image:
    needs: [ assemble ]
    uses: ministryofjustice/laa-ccms-common-workflows/.github/workflows/ecr-publish-image.yml@v1
    permissions:
      contents: read
      id-token: write
    with:
      jar_subproject: 'laa-submit-a-bulk-claim-ui'
      image_version: ${{ format('{0}-{1}', vars.IMAGE_PREFIX, needs.assemble.outputs.published_artifact_version) }}
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      ecr_repository: ${{ vars.ECR_REPOSITORY }}
      ecr_region: ${{ vars.ECR_REGION }}
      ecr_role_to_assume: ${{ secrets.ECR_ROLE_TO_ASSUME }}

  deploy-development:
    needs: [ ecr-publish-image ]
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/helm-deploy.yml
    with:
      environment: development
      deployment_name: development
      image_tag: ${{ needs.ecr-publish-image.outputs.published_image_version }}
    secrets: inherit

#  deploy-uat:
#    needs: [ ecr-publish-image ]
#    permissions:
#      id-token: write
#      contents: read
#    uses: ./.github/workflows/helm-deploy.yml
#    with:
#      environment: uat
#      deployment_name: uat
#      image_tag: ${{ needs.ecr-publish-image.outputs.published_image_version }}
#    secrets: inherit
#
#  deploy-staging:
#    needs: [ ecr-publish-image ]
#    permissions:
#      id-token: write
#      contents: read
#    uses: ./.github/workflows/helm-deploy.yml
#    with:
#      environment: staging
#      deployment_name: staging
#      image_tag: ${{ needs.ecr-publish-image.outputs.published_image_version }}
#    secrets: inherit
