name: e2e MBOYD

on:
  pull_request:

permissions:
  contents: read

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout laa-data-claims-parent
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          repository: ministryofjustice/laa-data-claims-parent
          path: laa-data-claims-parent
          ref: test/BC-671-e2e-pipeline # TODO: Remove
          submodules: 'true'

      - name: Update parent submodules
        working-directory: laa-data-claims-parent
        run: |
          ./update-bulk-claim-repos.sh
          cd laa-submit-a-bulk-claim          
          BRANCH="${{ github.head_ref || github.ref_name }}"
          git fetch origin "$BRANCH"
          git checkout -B "$BRANCH" FETCH_HEAD
          
          cd ../laa-data-claims-api
          git fetch origin test/BC-671-e2e-pipeline
          git checkout -B test/BC-671-e2e-pipeline FETCH_HEAD
          
          cd ../laa-data-claims-event-service
          git fetch origin task/BC-671-e2e-pipeline
          git checkout -B task/BC-671-e2e-pipeline FETCH_HEAD

      - name: Set up Java
        uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
        with:
          distribution: temurin
          java-version: '25'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
        with:
          cache-read-only: false # TODO: This is just for testing

      - name: Install Task
        uses: go-task/setup-task@01a4adf9db2d14c1de7a560f09170b6e0df736aa # v2.1.0

      - name: Build and start services
        working-directory: laa-data-claims-parent
        run: task up:submit
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }} # Required for providers-api dependency

#      - name: Build laa-submit-a-bulk-claim-ui
#        working-directory: laa-submit-a-bulk-claim
#        run:
#            ./gradlew :laa-submit-a-bulk-claim-ui:assemble --build-cache
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Build laa-data-claims-event-service
#        working-directory: laa-data-claims-parent/laa-data-claims-event-service
#        run:
#            ./gradlew assemble --build-cache
#        env:
#          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }} # Required for providers-api dependency
#
#      - name: Build laa-data-claims-api
#        working-directory: laa-data-claims-parent/laa-data-claims-api
#        run:
#            ./gradlew assemble --build-cache
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
