name: Test using E2E dispatch

on:
  workflow_call:
    inputs:
      sabc_image_tag:
        required: true
        type: string
      test_annotation:
        required: true
        type: string
      pr_number:
        required: false
        type: number
      github_app_organisation:
        required: false
        type: string
    secrets:
      github_app_id:
        required: false
      github_app_private_key:
        required: false

permissions:
  contents: read

jobs:

  get-app-token:
    runs-on: ubuntu-latest
    env:
      GITHUB_APP_ID: ${{ secrets.github_app_id }}
      GITHUB_APP_PRIVATE_KEY: ${{ secrets.github_app_private_key }}
    steps:

      - name: Get app token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v4
        with:
          application_id: ${{ secrets.github_app_id }}
          application_private_key: ${{ secrets.github_app_private_key }}
          organization: ${{ inputs.github_app_organisation }}

