name: Frontend dependency pipeline
on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  frontend-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get npm version
        id: npm
        run: echo "version=$(npm view govuk-frontend version)" >> $GITHUB_OUTPUT

      - name: Get current version
        id: current
        run: |
          VERSION=$(grep -oP "govuk-frontend:\K[0-9.]+" laa-submit-a-bulk-claim-ui/build.gradle)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if update needed
        id: compare
        run: |
          if [ "${{ steps.npm.outputs.version }}" != "${{ steps.current.outputs.version }}" ]; then
            echo "update_needed=true" >> $GITHUB_OUTPUT
          else
          echo "update_needed=false" >> $GITHUB_OUTPUT
          fi

      - name: Update version
        if: steps.compare.outputs.update_needed == 'true'
        run: |
          sed -i "s/govuk-frontend:${{ steps.current.outputs.version }}/govuk-frontend:${{ steps.npm.outputs.version }}/g" laa-submit-a-bulk-claim-ui/build.gradle

      - name: Create pull request
        if: steps.compare.outputs.update_needed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Update govuk-frontend to ${{ steps.npm.outputs.version }}"
          title: "Update govuk-frontend to ${{ steps.npm.outputs.version }}"
          body: "Automated update via pipeline"
          branch: update-govuk-frontend

        

